# Generated by Django 5.0.3 on 2024-03-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'Sub-Categories'},
        ),
        migrations.AlterField(
            model_name='asset',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, help_text='from 0 to 999,999,999.99', max_digits=11),
        ),
    ]
