# Generated by Django 5.0.3 on 2024-03-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0002_alter_category_options_alter_subcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='returned_date',
            field=models.DateField(blank=True),
        ),
    ]
