# Generated by Django 5.0.3 on 2024-03-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0003_alter_asset_returned_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='returned_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
