# Generated by Django 5.0.3 on 2024-03-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0004_alter_asset_returned_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='date',
            field=models.DateField(help_text='yyyy-mm-dd format', verbose_name='Purchase Date'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='obrNum',
            field=models.PositiveSmallIntegerField(verbose_name='OBR #'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='returned_date',
            field=models.DateField(blank=True, help_text='Please do not forget to add the return-date here if the asset was surrendered to GSO', null=True),
        ),
    ]
