# Generated by Django 5.0.3 on 2024-03-19 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Added by'),
        ),
        migrations.AlterField(
            model_name='item',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='added on'),
        ),
        migrations.AlterField(
            model_name='item',
            name='brand',
            field=models.CharField(max_length=100, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, verbose_name='modified on'),
        ),
        migrations.AlterField(
            model_name='item',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, help_text='from 0 to 999,999,999.99', max_digits=11, verbose_name='Price per Unit'),
        ),
        migrations.AlterField(
            model_name='item',
            name='qty',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Qty'),
        ),
        migrations.AlterField(
            model_name='item',
            name='returned_date',
            field=models.DateField(blank=True, help_text='Please do not forget to add the return-date here if the asset was surrendered to GSO', null=True, verbose_name='Return Date'),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(blank=True, choices=[('Working', 'Working'), ('Not Working', 'Not Working'), ('Turned Over to GSO', 'Turned Over to GSO')], default='Working', max_length=80, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.subcategory', verbose_name='Sub-Category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='supplier',
            field=models.CharField(max_length=100, verbose_name='Supplier'),
        ),
    ]
